default_platform :ios

platform :ios do
    desc "Translator"
    lane :distribute do
        build_ios_app(
          scheme: "Translator",
          workspace: "Translator.xcworkspace",
          export_method: "development"
        )

        firebase_app_distribution(
            app: "translator-33ca9",
            testers: "igorlnvch@gmail.com, alexandr.mihalkevich@gmail.com",
            release_notes: "Initial project"
        )

    end
end
