default_platform :ios

platform :ios do
    desc "Translator"
    lane :distribute do
        build_ios_app(
          scheme: "Translator",
          workspace: "Translator.xcworkspace",
          export_method: "development"
        )

        firebase_app_distribution(
            app: "1:990997999049:ios:ba4ca68e1c4338abc00c18",
            testers: "igorlnvch@gmail.com, alexandr.mihalkevich@gmail.com, translateskeo@gmail.com",
            release_notes: "Small refactor. Update libraries. More big updates very soon"
        )
    end
end
